version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./backend/app:/app/app

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - backend
    volumes:
      - ./frontend/app:/app/app